<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5UKM8NQ" failures="1" tests="5" name="selenium.scripts.SME.AggregatorToolAddandInviteSMEusers" time="13.310" errors="0" timestamp="2023-06-02T15:42:22 IST" skipped="0">
  <testcase classname="selenium.scripts.SME.AggregatorToolAddandInviteSMEusers" name="test_02AddanSMEuserPage" time="0.282"/>
  <system-out/>
  <testcase classname="selenium.scripts.SME.AggregatorToolAddandInviteSMEusers" name="test_03ValidateEnteredDetails" time="1.485"/>
  <system-out/>
  <testcase classname="selenium.scripts.SME.AggregatorToolAddandInviteSMEusers" name="test_04AddSMESuccessfulPage" time="0.950">
    <failure message="expected [Success!] but found [Error]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Success!] but found [Error]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at selenium.scripts.SME.AggregatorToolAddandInviteSMEusers.test_04AddSMESuccessfulPage(AggregatorToolAddandInviteSMEusers.java:75)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_04AddSMESuccessfulPage -->
  <system-out/>
  <testcase classname="selenium.scripts.SME.AggregatorToolAddandInviteSMEusers" name="test_01AggregatorToolLandingPage" time="9.524"/>
  <system-out/>
  <testcase classname="selenium.scripts.SME.AggregatorToolAddandInviteSMEusers" name="test_05SMEDetailsPage" time="1.069"/>
  <system-out/>
</testsuite> <!-- selenium.scripts.SME.AggregatorToolAddandInviteSMEusers -->
